const { chromium } = require("playwright");
(async () => {
  const S = process.argv[2]; const BASE = "http://127.0.0.1:" + (process.argv[3] || "8765");
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1200, height: 900 } });
  const errors = [];
  page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
  page.on("pageerror", (e) => errors.push(String(e)));
  await page.goto(BASE + "/");
  await page.waitForSelector("#q-text");
  await page.click("#ns-demo");
  await page.waitForSelector("#q-text");
  await page.click('a[data-tab="calibration"]');
  await page.waitForSelector("#demo");
  await page.click("#demo");
  await page.waitForSelector(".calib", { timeout: 120000 });
  await page.screenshot({ path: S + "/shot_calibration.png", fullPage: true });
  await page.click('a[data-tab="tournoi"]');
  await page.waitForSelector("table.tbl");
  console.log("tournoi:", (await page.textContent(".panel")).trim().slice(0, 120));
  await page.click('a[data-tab="prevoir"]');
  await page.fill("#q-text", "Le taux de chômage en France sera-t-il inférieur à 7 % au T2 2027 selon l'INSEE ?");
  await page.click("details.opt:nth-of-type(2) summary");
  await page.fill("#m-p", "35");
  await page.fill("#m-src", "Manifold, 4 oct. 2026");
  await page.click("#go-manual");
  await page.waitForSelector("#v-rule");
  await page.click("#v-ok");
  console.log("statut après clic sans règle:", await page.textContent("#status"));
  await page.fill("#v-rule", "OUI si le taux de chômage BIT publié par l'INSEE pour le T2 2027 est strictement inférieur à 7,0 %.");
  await page.fill("#v-src", "https://www.insee.fr/fr/statistiques");
  await page.fill("#v-dl", "2027-08-20");
  await page.fill("#v-hz", "P320D");
  await page.click("#v-ok");
  await page.waitForSelector(".pbig", { timeout: 60000 });
  console.log("p affichée:", await page.textContent(".pbig"));
  await page.screenshot({ path: S + "/shot_result.png", fullPage: true });
  await page.click('a[data-tab="registre"]');
  await page.waitForSelector("#verify");
  await page.click("#verify");
  await page.waitForSelector("#vres .panel");
  console.log("vérif:", (await page.textContent("#vres")).trim().slice(0, 100));
  await page.click(".ledger .open");
  await page.waitForSelector(".ledger details.opt summary");
  await page.click(".ledger details.opt summary");
  await page.click(".ledger .replay");
  await page.waitForSelector(".replay-out .chip");
  console.log("rejeu:", await page.textContent(".replay-out"));
  await page.emulateMedia({ colorScheme: "dark" });
  await page.click('a[data-tab="prevoir"]');
  await page.setViewportSize({ width: 400, height: 900 });
  await page.click('a[data-tab="calibration"]');
  await page.waitForSelector(".calib");
  await page.screenshot({ path: S + "/shot_dark_mobile.png", fullPage: false });
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  console.log("débordement horizontal mobile:", overflow);
  console.log("erreurs console:", errors.length ? errors : "aucune");
  await browser.close();
})().catch((e) => { console.error("ÉCHEC", e); process.exit(1); });
